create database ACCELERATE;
use ACCELERATE;
create table USERS(
	USERNAME VARCHAR(25) NOT NULL UNIQUE,
    PASSWD VARCHAR(150) NOT NULL,
    PUBLICKEY VARCHAR(150) NOT NULL,
    
    PRIMARY KEY (USERNAME)
);
